project:
  type: website
  output-dir: docs

website:
  title: "today"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, kiwamizamurai"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/kiwamizamurai/quarto-tutorial
          - text: Author
            href:  https://github.com/kiwamizamurai
  sidebar:
      style: "docked"
      search: true
      contents: auto
  repo-url: https://github.com/kiwamizamurai/quarto-tutorial
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true